version: "3.9"

services:
  app:
    container_name: crm
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - .:/crm
#    depends_on:
#      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
