import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

SECRET_KEY = os.getenv("SECRET_KEY")
ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES")

RESET_PASSWORD_TOKEN_SECRET = os.getenv("RESET_PASSWORD_TOKEN_SECRET")
VERIFICATION_PASSWORD_TOKEN_SECRET = os.getenv("VERIFICATION_PASSWORD_TOKEN_SECRET")


SUPER_USER_EMAIL = os.getenv("SUPER_USER_EMAIL")
SUPER_USER_PASSWORD = os.getenv("SUPER_USER_PASSWORD")
SUPER_USER_IS_ACTIVE = os.getenv("SUPER_USER_IS_ACTIVE")
SUPER_USER_IS_SUPERUSER = os.getenv("SUPER_USER_IS_SUPERUSER")
SUPER_USER_IS_VERIFIED = os.getenv("SUPER_USER_IS_VERIFIED")